google/cpu_features

include/cpuinfo_x86.h
src/cpuinfo_x86.c

with this patch the lib detect [sgx](https://en.wikipedia.org/wiki/Software_Guard_Extensions) and smx

detect intel sgx and smx cpu features for the x86 arch

---

include/cpuinfo_arm.h
src/cpuinfo_arm.c
test/cpuinfo_arm_test.cc

This is in preparation of adding [ndk_compat](https://github.com/google/cpu_features/issues/47)

Export GetArmCpuId function

---

CMakeLists.txt

Just add a PIC option: no change of behavior, default still OFF.

Add PIC option

---

include/internal/cpuid_x86.h
src/cpuinfo_x86.c
test/cpuinfo_x86_test.cc

(required E.g for leaf4)
P.S. I can try to add support for leaf4 soon.

Add x86 CpuIdEx function to pass inputs in ecx register

---

CMakeLists.txt

I've forgotten to add new file to CMakeLists.txt in https://github.com/google/cpu_features/pull/80.
(Sorry for this).
Can you, please also update the latest release?

Fix cmake install

---

src/utils/list_cpu_features.c

This is in preparation to include cache hierarchy in the dumped data.

[NFC] Use a tree structure in list_cpu_features

---

src/utils/list_cpu_features.c

Addressing comments in https://github.com/google/cpu_features/pull/94.
@digit-google can you take a look?

Address comments in https://github.com/google/cpu_features/pull/94

---

.gitignore
src/utils/list_cpu_features.c

This adds `cache_info` data to the output of `list_cpu_features`

Add cache_info data to X86 for list_cpu_features

---

CMakeLists.txt

Fix version mismatch in CMakeLists.txt

Bump version 0.1.0 -> 0.5.0 (Fix #118)

---

scripts/make_release.sh

Provides a release script

---

include/cpuinfo_aarch64.h
include/internal/hwcaps.h
src/cpuinfo_aarch64.c
test/cpuinfo_aarch64_test.cc

Update AArch64 features to Linux 5.10

---

src/cpuinfo_x86.c

This is a non functional change, it's a small refactoring with more comments so it's easier to follow along.

[NFC] refactor the code so it's easier to understand the execution flow

---

src/impl_x86__base_implementation.inl

This patch reads the most important cpuid leaves and stores the data in
a struct. A followup patch will inline micro architecture detection and
brand string inside X86Info so we don't have to call `ReadLeaves` multiple
times. This wil allow further simplification of `HasSecondFMA` and help
fix https://github.com/google/cpu_features/issues/200.

[NFC][x86] Read all cpuid leaves at once

---

src/impl_x86__base_implementation.inl
src/impl_x86_freebsd.c
src/impl_x86_linux_or_android.c
src/impl_x86_macos.c
src/impl_x86_windows.c
test/cpuinfo_x86_test.cc

https://github.com/google/cpu_features/issues/200

Fix list_cpu_features.exe does not detect SSE42 on Xeon X5650 (Windows)

---

.gitignore
BUILD.bazel
WORKSPACE
bazel/platforms.bzl

[NFC] Add bazel support to cpu_features

---

.github/workflows/amd64_windows.yml

Fix windows CI (related to ci issue in https://github.com/google/cpu_features/pull/218)

Fix windows amd64 ci

---

README.md
cmake/README.md
cmake/ci/vagrant/freebsd/Vagrantfile

note: github workflow CMake Linux/MacOS/Windows already call it.

Add install doc (Fix #238)

---

include/cpuinfo_mips.h
include/internal/hwcaps.h
src/impl_mips_linux_or_android.c
test/cpuinfo_mips_test.cc

This PR adds support for more MIPS features (mips16, mmdx, mips3d, smartmips, dsp).
I've tested it using Debian 11 on the QEMU MIPS emulator.

Added some MIPS features.

---

include/cpuinfo_x86.h
src/impl_x86__base_implementation.inl

add comet lake support #248

---

src/impl_x86__base_implementation.inl
test/cpuinfo_x86_test.cc

add missed AMD piledriver model 0x10

add amd piledriver 0x10 model

---

src/impl_x86__base_implementation.inl

We have already `break` into else branch, thus we can remove the repeated branch

Get rid repeated branch

---

include/cpuinfo_x86.h
src/impl_x86__base_implementation.inl
test/cpuinfo_x86_test.cc

add  AMD RX-8125, RX-8120, and A9-9820 detection

add amd cato

---

include/cpuinfo_x86.h
src/impl_x86__base_implementation.inl
test/cpuinfo_x86_test.cc

Should close
https://github.com/google/cpu_features/issues/260

Add support for detecting Intel CascadeLake CPUs

---

src/impl_x86__base_implementation.inl
test/cpuinfo_x86_test.cc

add mobile core flavor https://en.wikipedia.org/wiki/List_of_Intel_Core_processors

add mobile core flavor

---

include/cpuinfo_x86.h
src/impl_x86__base_implementation.inl
test/cpuinfo_x86_test.cc

https://en.wikichip.org/wiki/intel/cpuid
https://en.wikichip.org/wiki/intel/microarchitectures/raptor_lake

Add Intel Raptor Lake uarch detection

---

README.md

I've written some bindings for this project in Java, which I'm hoping will be useful for other people. Thanks for the great library!

Add cpu-features-jni Java bindings to README

---

CMakeLists.txt

Opening this in a replace for https://github.com/google/cpu_features/pull/303

Add ENABLE_INSTALL option to manage 'install' target

---

scripts/generate_badges.d

usage:
```sh
(cd scripts && ./generate_badges.d)
```
note: `./scripts/generate_badges.d` will fail

fix generate_badges.d

---

src/impl_aarch64_macos_or_iphone.c

Fixed asimd detection on OS X 15.3 

---

scripts/make_release.sh

- Make sure to commit `MODULE.bazel`
- Fail before tagging if the repo has unstaged or uncommited changes.

Fix scripts/make_release.sh
