include/cpuinfo_x86.h
See:
https://www.intel.com/content/www/us/en/design/products-and-solutions/processors-and-chipsets/platform-codenames.html
https://en.wikipedia.org/wiki/Cannon_Lake_(microarchitecture)
=> Fix spelling mistake for 'Cannon Lake'

CMakeLists.txt
Closes #7. Building as a shared library is as easy as passing `-DBUILD_SHARED_LIBS=ON`, but we also need `-fPIC` in that case. Thus in this PR I've added logic to set `-fPIC` when building shared libraries.
=> Use fPIC when building as a shared library

CMakeLists.txt
=> without cpu_features_macros.h in the install tree, the library cannot

src/cpuinfo_x86.c
[osxcross](https://github.com/tpoechtrager/osxcross) gives the following error, which also happens with [regular gcc on OS X](https://github.com/asmjit/asmjit/issues/78):
```
cpu_features/src/cpuinfo_x86.c:44:no such instruction: `XGETBV'
```
Changing to the byte form fixes that error, while still working properly.
=> Convert XGETBV to equivalent byte form in GetXCR0Eax

src/cpuinfo_x86.c, src/filesystem.c, src/string_view.c, src/utils/list_cpu_features.c, test/bit_utils_test.cc, test/filesystem_for_testing.cc, test/filesystem_for_testing.h
Visual C++ reported a number of warnings:
..\src\filesystem.c(27): warning C4996: '_open': This function or variable may be unsafe. Consider using _sopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
..\src\filesystem.c(34): warning C4267: 'function': conversion from 'size_t' to 'unsigned int', possible loss of data
..\src\string_view.c(25): warning C4244: 'return': conversion from '__int64' to 'int', possible loss of data
..\src\string_view.c(41): warning C4244: 'return': conversion from '__int64' to 'int', possible loss of data
..\src\utils\list_cpu_features.c(151): warning C4090: 'function': different 'const' qualifiers
..\src\cpuinfo_x86.c(67): warning C4244: 'return': conversion from 'unsigned __int64' to 'uint32_t', possible loss of …
=> Fix a few build warnings

include/cpuinfo_x86.h, src/cpuinfo_x86.c
Issue #97 is caused by the fact that the Family and Model numbers of Kaby Lake and Coffee Lake CPUs are the same. The only way I could see to work around that is by using their Stepping values to differentiate them. 
According to https://en.wikichip.org/wiki/intel/microarchitectures/kaby_lake and https://en.wikichip.org/wiki/intel/microarchitectures/coffee_lake, these are:
Kaby Lake Stepping values: 9,
Coffee Lake Stepping values: 10, 11, 12, 13
I'm quite new to Git and C so please give me any necessary feedback to improve this commit.
Fixes #97 
Edit:
I've also included code changes to properly detect Cannon Lake, Ice Lake and Whiskey Lake processors.
=> Differentiate between different Lake uarch

src/cpuinfo_x86.c
Follow up from #99. Forgot to add INTEL_WHL and INTEL_ICL to the GetX86MicroarchitectureName function.
=> Add INTEL_WHL and INTEL_ICL to uarch get name function

src/cpuinfo_x86.c
This is a mechanical change. This is to prevent error in argument ordering.
@fexolm Can you provide me with the source of the data you used for traceability?
=> [NFC] Use Designated Initializers

CMakeLists.txt
For customers using add_subdirectory() approach
related to #106
=> CMake: Add missing alias for cpu_feature

CMakeLists.txt, test/CMakeLists.txt
Fixes https://github.com/google/cpu_features/issues/109
=> CMake: Enable CXX compiler for tests only

CMakeLists.txt
Fixes https://github.com/google/cpu_features/issues/108
=> Fix shared build

include/cpuinfo_x86.h, src/cpuinfo_x86.c
This change adds new Ice Lake variants, Tiger Lake and Sapphire Rapids.  CPUID info is documented and has been tested.
=> add future Intel microarchitectures

include/cpuinfo_x86.h, src/cpuinfo_x86.c, test/cpuinfo_x86_test.cc
This change:
- detects AVX-512 BF16, introduced in Cooper Lake
- detects AVX-512 VP2INTERSECT, introduced in Tiger Lake
- detects AMX, introduced in Sapphire Rapids
This is documented and has been tested.
=> detect future Intel AVX/AMX features

ndk_compat/CMakeLists.txt
Should fix the issue.
We are using this macro: https://github.com/google/cpu_features/blob/c186ec53072de068cfd5fac46704d0dd760f0b61/CMakeLists.txt#L42-L50
here:
https://github.com/google/cpu_features/blob/c186ec53072de068cfd5fac46704d0dd760f0b61/ndk_compat/CMakeLists.txt#L17
Unfortunately `cpu-features.h` is in ndk-compat directory not in `root/include` directory...'
=> Fix ndk-compat include directory (Fix #106)

src/utils/list_cpu_features.c
There is a small typo in src/utils/list_cpu_features.c.
Should read `intended` rather than `intented`.
=> docs: fix simple typo, intented -> intended

.github/workflows/Dockerfile
addressed https://github.com/google/cpu_features/pull/153#issuecomment-814456058, fix install `clang-format` binary to use `clang-extra-tools` package.
=> github/workflows: fix install clang-format to use clang-extra-tools pkg

README.md
The correct namespace is `cpu_features` as defined in: https://github.com/google/cpu_features/blob/3cc8f310d950b44cc6d2ead8057cf43330a726fd/include/cpu_features_macros.h#L108
=> Fix C++ namespace in README

include/cpuinfo_x86.h, src/cpuinfo_x86.c, test/cpuinfo_x86_test.cc
Intel has added ADOX, ADCX instructions to Broadwell microarchitecture. They are quite useful in cryptographic applications where two addition chains are being performed in parallel. 
Both Intel and AMD (Ryzen) support those instructions.
https://en.wikipedia.org/wiki/CPUID
=> Detect Intel's Multi-Precision Add-Carry Instruction Extensions

src/cpuinfo_x86.c
Detect AVX512 on Darwin use GetDarwinSysCtlByName("hw.optional.avx512f")
On the below CPU, darwin support AVX512 with on-demand.
- https://github.com/apple/darwin-xnu/blob/xnu-7195.81.3/osfmk/i386/fpu.c#L173-L199
```
arch            : x86
brand           : Intel(R) Xeon(R) W-2150B CPU @ 3.00GHz
family          :   6 (0x06)
model           :  85 (0x55)
stepping        :   4 (0x04)
uarch           : INTEL_SKL
.
.
```
sysctl result is here:
```console
$ sysctl hw.optional | grep avx512
hw.optional.avx512bw: 1
hw.optional.avx512cd: 1
hw.optional.avx512dq: 1
hw.optional.avx512f: 1
hw.optional.avx512ifma: 0
hw.optional.avx512vbmi: 0
hw.optional.avx512vl: 1
```
So, detect `os_support.have_avx512` to use `GetDarwinSysCtlByName("hw.optional.avx512f");`, support Intel(R) Xeon AVX512 on Darwin OS. …
=> Detect AVX512 on Darwin use GetDarwinSysCtlByName("hw.optional.avx512f")

include/cpu_features_macros.h, src/utils/list_cpu_features.c
The build fails with following message when -Werror
and -Werror=return-type are enabled.
In function ‘GetCacheTypeString’:
error: control reaches end of non-void function [-Werror=return-type]
Simple fix is to return 0 from that function. The
return value is then checked by an assert in the
AddMapEntry. The assert will only work in debug mode,
but that seems to be enough.
=> fix: Return default value from ‘GetCacheTypeString’

CMakeLists.txt
Fix #169 
note: this is the default behaviour when using `include(CTest)`
=> cmake: use CTest default

BUILD.bazel
Include paths should be specified through includes
rather than copts, so that they are handled correctly when
cpu_features is included in another project as an external repository.
=> Fix include paths in BUILD

src/impl_x86_linux_or_android.c, test/cpuinfo_x86_test.cc
See issue https://github.com/google/cpu_features/issues/224
Thanks.
=> replace sse3 detection with pni when reading /proc/cpuinfo

.github/workflows/amd64_bazel_linux.yml, WORKSPACE
* [optional] Use `git_repository()` to retrieve dependencies
* Add amd64 Linux Bazel based build jobs.
=> ci: Add bazel jobs

include/cpuinfo_aarch64.h, include/internal/hwcaps.h, src/impl_aarch64_linux_or_android.c, test/cpuinfo_aarch64_test.cc
Adds three new features: ecv, afp and rpres.
=> Update AArch64 features to Linux 5.17.

include/cpu_features_macros.h
Added a #define for if the compiler supports the MIPS3D ASE.
I have tested this with gcc.
=> Added CPU_FEATURES_COMPILED_MIPS_MIPS3D.

include/cpuinfo_x86.h, src/impl_x86__base_implementation.inl, test/cpuinfo_x86_test.cc
In this PR I added uarch detection to Zen 4, and updated Zen 3, Hygon
Zen 4: https://en.wikichip.org/wiki/amd/cpuid
Zen 3: 
* Threadripper 5900 "Chagall" (sWRX8), see https://en.wikichip.org/wiki/amd/cpuid (Family: 25, Model: 0x08)
* Engineering Sample ([SP3](https://en.wikichip.org/wiki/amd/packages/sp3)), see https://en.wikichip.org/wiki/amd/cpuid (Family: 25, Model: 0x00)
* OctalCore AMD Ryzen 9 6900HX  [Rembrandt Cpuid Dump](http://users.atw.hu/instlatx64/AuthenticAMD/AuthenticAMD0A40F41_K19_Rembrandt_03_CPUID.txt) (Family:  0x19, Model: 0x44)
OctalCore Hygon C86 3250: [Cpuid Dump](http://users.atw.hu/instlatx64/HygonGenuine/HygonGenuine0900F11_Hygon_01_CPUID.txt) (Family:  0x18, Model: 0x01)
=> Add AMD ZEN 4 uarch and update detection

include/cpu_features_macros.h
Add macros that test which RISCV features have been enabled at compile time.
This patch has been tested with clang version 14.0.0 (and should also work with gcc).
clang does not currently support 128 bit integer registers (CPU_FEATURES_ARCH_RISCV128) or 128 bit floating point registers (CPU_FEATURES_COMPILED_RISCV_Q); all the other features are supported by clang 14.0.0.
These features are all either in the ratified version of the RISCV Unprivileged specification, or are ratified extensions. (the V vector extension, Zb bitmap extensions, and Zk crypto extensions were ratified in November 2021). i.e. they are all officially part of the RISCV spec.
=> Add macros for RISCV features

include/cpu_features_macros.h, src/utils/list_cpu_features.c, test/cpuinfo_x86_test.cc
- get rid of deprecated funciton usage warning (though FillX86BrandString still available - let's not use it by ourself)
- add MSVC deprecation mark support
=> remove internal FillX86BrandString usage

include/cpuinfo_x86.h, src/impl_x86__base_implementation.inl, test/cpuinfo_x86_test.cc
https://github.com/google/cpu_features/issues/253
=> Add detection LZCNT

test/cpuinfo_aarch64_test.cc, test/cpuinfo_arm_test.cc, test/cpuinfo_mips_test.cc, test/cpuinfo_ppc_test.cc, test/cpuinfo_x86_test.cc
allows to check for LINE( presense in x86 feature and microarch arrays
=> test enum macro consistency

include/cpuinfo_x86.h, src/impl_x86__base_implementation.inl, test/cpuinfo_x86_test.cc
https://github.com/google/cpu_features/issues/263
=> Add AVX_VNNI support

include/cpuinfo_x86.h, src/impl_x86__base_implementation.inl
According to https://en.wikichip.org/wiki/amd/cpuid I added detection of the following AMD uarch:
- ~Added family 0x18 model 0x00 to zen architecture~ 
- ~Moved family 0x17 model 0x18 from zen to zen plus architecture~
- ~Added family 0x15 model 0x10 to piledriver architecture~
- Created identifier for AMD_LLANO and added family 0x12 model 0x00 to it (Does it have to be merged with K12?)
EDIT: merged with K12
=> Added some missing amd uarch

test/cpuinfo_x86_test.cc
I have added in this PR replacing of hardcoded values to constants `CPU_FEATURES_VENDOR_GENUINE_INTEL`, `CPU_FEATURES_VENDOR_AUTHENTIC_AMD` and `CPU_FEATURES_VENDOR_HYGON_GENUINE`
ref: https://github.com/google/cpu_features/blob/426b036e8dc04a296c8e837745d7fa187f57670d/include/cpuinfo_x86.h#L24-L29
=> Replace hardcoded values ​​to constants for X86 tests.

src/impl_x86__base_implementation.inl, test/cpuinfo_x86_test.cc
In this pull request I added cache info detection for old AMD processors. We can get information about the TLB, but I don't know how to process this information as there is a difference in leaves, there is information for 4KB, 2MB, 4MB, 1GB pages, so I have defined these fields as UNDEF so far
=> Add cache detection for old AMD processors

include/cpuinfo_x86.h, src/impl_x86__base_implementation.inl, test/cpuinfo_x86_test.cc
For reference, on an alder-lake CPU with `AVX512` (and therefore, `AVX512_FP16` support) enabled:
```shell
$ ./list_cpu_features
arch            : x86
brand           : 12th Gen Intel(R) Core(TM) i9-12900K
family          :   6 (0x06)
model           : 151 (0x97)
stepping        :   2 (0x02)
uarch           : INTEL_ADL
flags           : adx,aes,avx,avx2,avx512_bf16,avx512_fp16,avx512_second_fma,avx512_vp2intersect,avx512bitalg,avx512bw,avx512cd,avx512dq,avx512f,avx512ifma,avx512vbmi,avx512vbmi2,avx512vl,avx512vnni,avx512vpopcntdq,avx_vnni,bmi1,bmi2,clflushopt,clfsh,clwb,cx16,cx8,erms,f16c,fma3,fpu,lzcnt,mmx,movbe,pclmulqdq,popcnt,rdrnd,rdseed,sha,smx,ss,sse,sse2,sse3,sse4_1,sse4_2,ssse3,tsc,vaes,vpclmulqdq
cache_info      : {"level":1,"cache_type":"data","cache_size":49152,"ways":12,"line_ …
```
=> add x86/avx512_fp16 detection

include/cpuinfo_x86.h, src/impl_x86__base_implementation.inl, test/cpuinfo_x86_test.cc
In this PR I added GFNI detection:
Intel® 64 and IA-32 Architectures Software Developer’s Manual Volume 2 Page 323
CPUID.0000_0007_ECX[8]: GFNI support
=> Add X86 GFNI detection

include/cpuinfo_x86.h, src/impl_x86__base_implementation.inl, test/cpuinfo_x86_test.cc
In this PR I added the detection of movdir instructions
refs:
https://www.felixcloutier.com/x86/movdiri
https://www.felixcloutier.com/x86/movdir64b
[architecture-instruction-set-extensions-programming-reference page 26](https://software.intel.com/sites/default/files/managed/c5/15/architecture-instruction-set-extensions-programming-reference.pdf)
=> Add X86 MOVDIRI/MOVDIR64B detection

include/cpuinfo_x86.h, src/impl_x86__base_implementation.inl, test/cpuinfo_x86_test.cc
In this PR I added the detection of rep instructions:
* Fast Short REP MOV
* Fast zero-length REP MOVSB
* Fast short REP STOSB
* Fast short REP CMPSB/SCASB
_Note:_
I didn't find cpuid dump with REP MOVSB and REP CMPSB/SCASB only added alder lake where we have Fast short REP STOSB/ Fast Short REP MOV
=> Add REP instructions detection

.github/workflows/aarch64_linux_cmake.yml, .github/workflows/power_linux_cmake.yml, cmake/ci/Makefile, scripts/run_integration.sh, src/impl_ppc_linux.c
Few updates
* cleanup scripts
* Add Aarch64 bootlin support (script, cmake/ci, workflows)
* Add Power bootlin support (script, cmake/ci, workflows)
=> Improve CI (Aarch64, Power)

scripts/run_integration.sh
We may be able to use [CMAKE_CROSSCOMPILING_EMULATOR](https://cmake.org/cmake/help/latest/variable/CMAKE_CROSSCOMPILING_EMULATOR.html) in the future but it's easier to just use run the tests under qemu.
BTW it may be necessary to enclose qemu's run with a `set -e` / `set +e`.
=> Include tests when using QEMU

CMakeLists.txt
Since 1.13.0, gtest requires at least C++14. When it is automatically downloaded and compiled, gtest’s CMake scripts override the C++ standard, so the tests are compiled in C++14 mode already. Changing the C++ standard in cpu_features will make it easier for users such as Linux distribution packagers who are linking against an external or system-wide copy of gtest 1.13.0 or later.
=> Update C++ standard for tests from C++11 to C++14

CMakeLists.txt
Hopefully this is self explanatory.
When using FetchContent with CMake/CPM this will prevent automatically discovering and building tests.
The option to force this is still preserved by proviing `BUILD_TESTING` as an externally settable option
=> cmake: make default test building dependent on being a main project build vs. being included into other projects

BUILD.bazel
Add 'ndk_compat' to the 'includes' directive of the 'ndk_compat' target, so that targets that include this library can directly reference 'cpu-features.h' like they did with the legacy Android NDK library.
=> Add 'ndk_compat' include directory to 'ndk_compat' target

BUILD.bazel, bazel/platforms.bzl
The CMake builds are already supported, this just forwards those rules into the Bazel BUILD.
=> Add Riscv32 and Riscv64 Bazel build rules.

CMakeLists.txt, cmake/README.md
Use `CpuFeatures::` for ALIAS since this is the name we already use for `install(EXPORT)`...
note: currently CI test using cmake install step, I don't know if we should also add a job to check if using `CpuFeatures::cpu_features` using `add_subdirectory()`/`FetchContent()` is also working as expected (both will rely on the `ALIAS`...)
=> cmake: Use CpuFeatures:: as TARGET namespace (Fix #333)

include/cpuinfo_x86.h, src/impl_x86__base_implementation.inl
https://cdrdv2-public.intel.com/774990/architecture-instruction-set-extensions-programming-reference.pdf
this instruction set will be in future Granite Rapids (~2024-2025)
llvm https://github.com/llvm/llvm-project/blob/9f3e3efd98a29eb8df9e3ad43a573c9141d1ace2/clang/lib/Basic/Targets/X86.cpp#L834
=> Add Intel AMX-FP16 detection

src/hwcaps_linux_or_android.c
note: tested using: `add_compile_options("-Werror" "-Wstrict-prototypes")`
=> fix -Wstrict-prototypes error

cmake/ci/docker/amd64/Dockerfile, cmake/ci/docker/toolchain/Dockerfile, scripts/run_integration.sh
* Updated deprecated qemu-download url to new https://download.qemu.org/
* Updated QEMU version from 7.1.0 to 9.0.2 (latest)
* Fixed error `Python's ensurepip module is not found.`
Proof of success:
* powerpc: https://github.com/toor1245/cpu_features/actions/runs/10550675548
* mips: https://github.com/toor1245/cpu_features/actions/runs/10550675550
=> Fix run_integration.sh

include/cpu_features_macros.h
ARM Architecture Reference Manual suggests to check for the presence of the Advanced SIMD instructions via `__ARM_NEON`
=> Fix wrong arm neon detection

.github/workflows/amd64_macos_bazel.yml, .github/workflows/amd64_macos_cmake.yml
Github Actions added support M1, thus macOS supports arm64 and amd64 in actions:
* `macos-latest` is arm64 architecture
* `macos-13` is amd64 architecture 
see details:
https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
it looks like `macos-latest-large` is not supported to use amd64
https://github.com/actions/runner-images?tab=readme-ov-file#available-images
Also, we should add CI/CD arm64 architecture support for macOS M1 CPUs in the separate patch and fix tests.
See details: https://github.com/google/cpu_features/actions/runs/10499466482/job/29086289583
```shell
Running main() from gmock_main.cc
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from …
```
=> Update amd64 macos workflow to use X86 arch

BUILD.bazel
We don't have mock compilation definitions for bazel, so our tests will get real CPU information and the tests will fail:
https://github.com/toor1245/cpu_features/actions/runs/10551510292/job/29229039421#step:6:23
```
FAIL: //:cpuinfo_test (see /private/var/tmp/_bazel_runner/9528e8115d3e1528a3dc7979ba042b2f/execroot/_main/bazel-out/darwin_arm64-opt/testlogs/cpuinfo_test/test.log)
==================== Test output for //:cpuinfo_test:
INFO: From Testing //:cpuinfo_test:
Running main() from gmock_main.cc
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from CpuidAarch64Test
[ RUN      ] CpuidAarch64Test.Aarch64FeaturesEnum
[       OK ] CpuidAarch64Test.Aarch64FeaturesEnum (0 ms)
[ RUN      ] …
```
=> Fix bazel build testing for macos arm64

include/cpu_features_macros.h
On MSVC for ARM/ARM64, __ARM_NEON is not defined. However, Windows requires NEON on ARM, so it should be safe to assume that if CPU_FEATURES_ARCH_ANY_ARM is defined and we're in MSVC, NEON is also available.
There may be a better way to do this, but this patch has helped get my project running at full speed on Windows ARM64 machines and wanted to share. Thanks for this great library!
=> Fix: Windows does not define __ARM_NEON

include/cpu_features_macros.h
This is a fix for https://github.com/google/cpu_features/pull/363 . The preprocessor check must be done in two steps.
=> Forward fix `cpu_features_macros.h`

.bazelrc, BUILD.bazel, bazel/ci/docker/Dockerfile
Requiring c99 for everyone breaks downstream users.
=> Move `c99` flag from BUILD file to bazel cmd line

CMakeLists.txt
cpu_features requires CMake 3.13 which sets CMP0077 always to NEW.
=> cmake: Remove useless check for CMP0077

MODULE.bazel
This is required with Bazel 8 that drops the support for WORKSPACE file.
=> [bazel] Add missing platform dependency

.github/workflows/aarch64_linux_cmake.yml, .github/workflows/arm_linux_cmake.yml, cmake/ci/Makefile, scripts/run_integration.sh
All toolchains have not been updated since 2019...
Also linaro website do not advertise them...
ref: https://www.linaro.org/downloads
note: new link point to https://snapshots.linaro.org/gnu-toolchain/ which only provide two flavors (aarch64 and arm-gnueabihf (ed also provided by bootlin)) with a warning disclaimer:
> These builds are for experimental environments only. They will break your stuff and drink all your beer. You have been warned.
ref: https://snapshots.linaro.org/gnu-toolchain/14.0-2023.06-1/
=> ci: Remove linaro toolchains support

src/utils/list_cpu_features.c
`vsnprintf` returns the number of printed characters _excluding_ the written `\0`. This leads to the next value overwriting the last `\0`, which in turn can print spurious characters to the output.
Fixes #373.
=> Fix allocator bump in printf string allocation

CMakeLists.txt, cmake/ci/README.md, include/cpuinfo_ppc.h, include/cpuinfo_x86.h, ndk_compat/cpu-features.h, scripts/make_release.sh, src/impl_ppc_linux.c, test/cpuinfo_mips_test.cc
% `codespell --ignore-words-list=hart,sie,sme,te,tha --write-changes`
* https://github.com/codespell-project/codespell
=> Fix typos discovered by codespell

.github/workflows/aarch64_linux_bazel.yml
[Standard GitHub-hosted runners for public repositories](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) --> `ubuntu-24.04-arm`
Accelerate the longest running GitHub Action job.
Currently, the `aarch64_linux_bazel` job takes three times longer to run than the other GitHub Actions jobs.
=> Run GitHub Workflow aarch64_linux_bazel on an ARM processor

CMakeLists.txt, test/CMakeLists.txt
Moving from "mandatory c++14" to "at least c++14".
=> Change test c++ standard handling

include/cpu_features_macros.h
=> Fix broken `CPU_FEATURES_OS_MACOS` and `CPU_FEATURES_OS_IPHONE` detection
